name: Test & Build MQTT Service

on:
  push:
    branches: [master]
    paths:
      - 'backend/mqtt-service/**'

defaults:
  run:
    working-directory: backend/mqtt-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image & Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: backend/mqtt-service
          tags: rangerdigital/canute-mqtt:latest
