name: Test & Build MQTT Bridge

on:
  push:
    branches: [master]
    paths:
      - 'mqtt-bridge/**'

defaults:
  run:
    working-directory: mqtt-bridge

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image & Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./mqtt-bridge
          tags: rangerdigital/canute-mqtt:latest
